import { type NextPage } from "next";
import Head from "next/head";
import { useMetamask } from "../../context/MetamaskProvider";

const ConnectWallet: NextPage = () => {
  const metamask = useMetamask();

  return (
    <>
      <Head>
        <title>Prophet | Connect</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center">
        <div className="container mx-auto flex flex-col items-center justify-center gap-12 px-4">
          <h1 className="text-3xl font-semibold tracking-wide text-white">
            Connect your wallet
          </h1>

          <button
            onClick={metamask?.connectWallet}
            className="flex items-center gap-4 rounded-xl bg-purple-500 px-8 py-4 font-semibold text-white heropattern-topography-white/10 hover:bg-purple-600"
          >
            <span className="text-xl">🦊</span>
            <span>Connect MetaMask</span>
          </button>
        </div>
      </main>
    </>
  );
};

export default ConnectWallet;
