import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";

import { Avatar } from "../components/Avatar";

const Home: NextPage = () => {
  const auctions = api.auctions.getAll.useQuery();

  console.log(auctions.data);

  return (
    <>
      <Head>
        <title>Prophet | Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Prophet
          </h1>
          <div className="flex w-full flex-col">
            {auctions.data?.map((auction) => (
              <Link
                key={auction.informationCID}
                className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/usage/first-steps"
                target="_blank"
              >
                <div className="flex items-center justify-between">
                  <h3 className="text-2xl font-bold">
                    {auction.information.title}
                  </h3>

                  <span>Information CID: {auction.information.CID}</span>
                  <Avatar seed={auction.information.ownerAddress} />
                </div>
                <div className="text-lg">{auction.information.description}</div>
              </Link>
            ))}
          </div>
          <p className="text-2xl text-white">
            {auctions.data ? "" : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
