import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";

import { Grid } from "../components/Grid";
import { AuctionCard } from "../components/cards/AuctionCard";

const Home: NextPage = () => {
  const auctions = api.auctions.getAll.useQuery();

  console.log(auctions.data);

  return (
    <>
      <Head>
        <title>Prophet | Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Prophet
          </h1>
          <Grid
            items={auctions.data || []}
            renderItem={(auction) => (
              <AuctionCard
                key={auction.informationCID}
                title={auction.information.title}
                description={auction.information.description}
                informationCID={auction.informationCID}
                sellerAddress={auction.information.ownerAddress}
                sellerReputation={Math.random() * 10}
                highestBid={Math.random() * 100}
              />
            )}
          />
          <p className="text-2xl text-white">
            {auctions.data ? "" : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
